name: Code coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run coverage
      run: tox -ecoverage
